### ISSUE TITLE
TASK 1 - error running 'rgridpair link' command with numbered passwords

### ISSUE THREAD

**Issue by simwilso** [redgridone/redgrid-cli#2]
there is an issue running the program if the users WiFi pwd is a number even when we put "" or '' around it.
This only happens when the pwd is ALL numbers i.e. if the pwd is '123' it fails but if the pwd is 123b it works.
Can we update so that the programs sends the Pwd as a string.

Error from Tuya API is that they expect a string and got a number:

```
 ⠼ Connected to TUYA cloud. Searching for device to pair...(node:62472) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received type number (77017383)
    at Function.from (buffer.js:327:9)
    at TuyaLink.smartLinkEncode (/Users/simonwilson/code/redgrid-cli/node_modules/@tuyapi/link/lib/link.js:156:38)
    at TuyaLink.registerSmartLink (/Users/simonwilson/code/redgrid-cli/node_modules/@tuyapi/link/lib/link.js:73:39)
(node:62472) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:62472) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by simwilso** [comment]
also had another issue similar to this today running with the rgridpair-macos application.  This time the error we received was the same but related to the 'key' value and it says it received null:

`The argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received type null`
